### ISSUE TITLE
[V3] Tracking issue

### ISSUE THREAD

**Issue by MierenManz** [harmonyland/harmony#219]
# Harmony v3

### @Helloyunho, @DjDeveloperr 
- [ ] Application
- [ ] Audit Log
- [ ] Channel
- [ ] Emoji
- [ ] Guild
- [ ] Guild Template
- [ ] Invite
- [ ] Stage Instance
- [ ] Sticker
- [ ] User
- [ ] Voice
- [ ] Webhook
- [ ] Gateway

### @Helloyunho, @DjDeveloperr 
- [ ] Implement `HTTPClient`
- [ ] `RESTClient` (blocked by `HTTPClient` and types)
- [ ] `GatewayClient` (blocked by types)
- [ ] `ShardedClient` (blocked by `GatewayClient`)
- [ ] Implement `APIManager` (blocked by RESTClient and `ShardedClient`)

### Blocked by Core
- [ ] Implement `Client`
- [ ] Implement Cache API
- [ ] Implement Structures
- [ ] Implement Managers
- [ ] Implement Abstracted REST Endpoints
- [ ] Implement Abstracted Gateway Events

## `ext`
- [ ] Implement a Redis Cache Adapter (blocked by Framework)
- More TBD

## `manual`
- [ ] Write beginners guide
- [ ] Write Examples of common code
- [ ] Write Explanation of harmony
- More TBD
