### ISSUE TITLE
[V3] Tracking issue

### ISSUE THREAD

**Issue by Helloyunho** [harmonyland/harmony#225]
Copy of #219, Also closes #219

# Harmony v3

### @Helloyunho, @DjDeveloperr 
- [ ] Application
- [ ] Audit Log
- [ ] Channel
- [ ] Emoji
- [ ] Guild
- [ ] Guild Template
- [ ] Invite
- [ ] Stage Instance
- [ ] Sticker
- [ ] User
- [ ] Voice
- [ ] Webhook
- [ ] Gateway

### @Helloyunho, @DjDeveloperr 
- [ ] Implement `HTTPClient`
- [ ] `RESTClient` (blocked by `HTTPClient` and types)
- [ ] `GatewayClient` (blocked by types)
- [ ] `ShardedClient` (blocked by `GatewayClient`)
- [ ] Implement `APIManager` (blocked by RESTClient and `ShardedClient`)

### Blocked by Core
- [ ] Implement `Client`
- [ ] Implement Cache API
- [ ] Implement Structures
- [ ] Implement Managers
- [ ] Implement Abstracted REST Endpoints
- [ ] Implement Abstracted Gateway Events

## `ext`
- [ ] Implement a Redis Cache Adapter (blocked by Framework)
- More TBD

## `manual`
- [ ] Write beginners guide
- [ ] Write Examples of common code
- [ ] Write Explanation of harmony
- More TBD

**Comment by MierenManz** [comment]
>  Implement a Redis Cache Adapter (blocked by Framework)
This can probably be renamed to
> Implement a Redis Cache store (blocked by Framework)
And we could also add this one under my name if we still want it
> Implement Binary Tree Cache store (blocked by Framework)

**Comment by DjDeveloperr** [comment]
@MierenManz 

> This can probably be renamed to

Done.

> And we could also add this one under my name if we still want it

Added.

Also added a note about unit tests, would it close #125 ?
