### ISSUE TITLE
TODO: Fully integrate Discord API

### ISSUE THREAD

**Issue by Helloyunho** [harmonyland/harmony#86]
Thanks to @ZiomaleQ for giving us this list.

# Guild:

- [x] [Create Guild](https://discord.com/developers/docs/resources/guild#create-guild)
- [x] [Guild Preview](https://discord.com/developers/docs/resources/guild#guild-preview-object)
- [x] [Modify Guild](https://discord.com/developers/docs/resources/guild#modify-guild)
- [x] [Delete Guild](https://discord.com/developers/docs/resources/guild#delete-guild)
- [x] [Modify Guild Channel Position**s**](https://discord.com/developers/docs/resources/guild#modify-guild-channel-positions)
- [x] [~~Add Guild Member~~ (Not for now because it requires OAuth2 token)](https://discord.com/developers/docs/resources/guild#add-guild-member)
- [x] [Add Guild Member Role](https://discord.com/developers/docs/resources/guild#add-guild-member-role)
- [x] [Remove Guild Member Role](https://discord.com/developers/docs/resources/guild#remove-guild-member-role)
- [x] [Modify Guild Role Position**s**](https://discord.com/developers/docs/resources/guild#modify-guild-role-positions)
- [x] [Modify Guild Role](https://discord.com/developers/docs/resources/guild#modify-guild-role)
- [x] [Get Guild Prune Count](https://discord.com/developers/docs/resources/guild#get-guild-prune-count)
- [x] [Begin Guild Prune](https://discord.com/developers/docs/resources/guild#begin-guild-prune)
- [x] [Create Guild Intergration](https://discord.com/developers/docs/resources/guild#create-guild-integration)
- [x] [Modify Guild Intergration](https://discord.com/developers/docs/resources/guild#modify-guild-integration)
- [x] [Delete Guild Intergration](https://discord.com/developers/docs/resources/guild#delete-guild-integration)
- [x] [Sync Guild Intergration](https://discord.com/developers/docs/resources/guild#sync-guild-integration)
- [x] [Modify Guild Widget](https://discord.com/developers/docs/resources/guild#modify-guild-widget)
- [x] [Get Guild Widget](https://discord.com/developers/docs/resources/guild#get-guild-widget)
- [x] [Get Guild Vanity URL](https://discord.com/developers/docs/resources/guild#get-guild-vanity-url)
- [x] [Get Guild Widget Image](https://discord.com/developers/docs/resources/guild#get-guild-widget-image)
- [x] [Leave Guild](https://discord.com/developers/docs/resources/user#leave-guild)

# Template:

- [x] [Get Template](https://discord.com/developers/docs/resources/template#get-template)
- [x] [Create Guild From Template](https://discord.com/developers/docs/resources/template#create-guild-from-template)
- [x] [Get Guild Templates](https://discord.com/developers/docs/resources/template#get-guild-templates)
- [x] [Create Guild Template](https://discord.com/developers/docs/resources/template#create-guild-template)

# Client:

- [x] [Modify Bot User](https://discord.com/developers/docs/resources/user#modify-current-user)
- [x] [~~Get Bot DMs~~ no longer possible for bots](https://discord.com/developers/docs/resources/user#get-user-dms)
- [x] [Create DM](https://discord.com/developers/docs/resources/user#create-dm)

# Voice:

- [x] [List Voice Regions](https://discord.com/developers/docs/resources/voice#list-voice-regions)

**Comment by DjDeveloperr** [comment]
Completed.
